---


- name: INSTALL | install firewalld
  yum:
    name: firewalld
    state: present
    update_cache: no
  when: ansible_pkg_mgr in ['yum', 'dnf']


- name: CONFIG | Enable firewalld
  service: 
    name: firewalld
    state: started
    enabled: yes
  no_log: true

