---

- name: INSTALL | default yum/dnf packages
  yum:
    name: yum-utils
    state: present
    update_cache: no
  when: ansible_pkg_mgr in ['yum', 'dnf']


- name: INSTALL | Add docker repository
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  register: add_docker_repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo


- name: INSTALL | default yum/dnf packages
  yum:
    update_cache: yes
  when: add_docker_repo is changed and ansible_pkg_mgr in ['yum', 'dnf']


- name: INSTALL | install docker
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: no
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  when: ansible_pkg_mgr in ['yum', 'dnf']